--22120016--
--Tran Hung Anh--

CREATE DATABASE QLKH;

USE QLKH;

CREATE TABLE BaiBao (
    IDBaiBao CHAR(10) NOT NULL,
    TenBaiBao NVARCHAR(50) NOT NULL,
    IDTruong CHAR(10) NOT NULL,
    IDPhanBien CHAR(10) NOT NULL
);

CREATE TABLE NhaKhoaHoc (
    IDNhaKhoaHoc CHAR(10) NOT NULL,
    IDTruong CHAR(10) NOT NULL,
    HoTen NVARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL
);

CREATE TABLE THAMGIA (
    IDBaiBao CHAR(10) NOT NULL,
    IDNhaKhoaHoc CHAR(10) NOT NULL,
    IDTruong CHAR(10) NOT NULL,
    ThanhTich NVARCHAR(50) NOT NULL CHECK (ThanhTich IN (N'Xuất sắc', N'Giỏi', N'Trung bình', N'Khá'))
)

ALTER TABLE BaiBao
ADD CONSTRAINT PK_PB
PRIMARY KEY(IDBaiBao, IDTruong, IDPhanBien);

ALTER TABLE NhaKhoaHoc
ADD CONSTRAINT PK_NKH
PRIMARY KEY(IDTruong, IDNhaKhoaHoc);

ALTER TABLE THAMGIA
ADD CONSTRAINT PK_TG
PRIMARY KEY(IDBaiBao, IDTruong, IDNhaKhoaHoc);

ALTER TABLE BaiBao
ADD CONSTRAINT FK_PB
FOREIGN KEY(IDTruong, IDPhanBien) REFERENCES NhaKhoaHoc(IDTruong, IDNhaKhoaHoc);

ALTER TABLE THAMGIA
ADD CONSTRAINT FK_TG_BB
FOREIGN KEY(IDBaiBao, IDTruong) REFERENCES BaiBao(IDBaiBao, IDTruong);

INSERT INTO NhaKhoaHoc VALUES ('N2', 'TN', N'Nguyễn', '07/15/1984');
INSERT INTO NhaKhoaHoc VALUES ('N2', 'BK', N'Tín', '09/26/1983');
INSERT INTO NhaKhoaHoc VALUES ('N1', 'BK', N'Hà', '10/18/1984');
INSERT INTO NhaKhoaHoc VALUES ('N1', 'TN', N'Hữu', '12/09/1984');
INSERT INTO NhaKhoaHoc VALUES ('N3', 'BK', N'Nhân', '12/01/1982');

INSERT INTO BaiBao VALUES ('B1', 'TN', N'Phát triển TPTM', 'N2');
INSERT INTO BaiBao VALUES ('B1', 'BK', N'Nghiên cứu BI', 'N2');
INSERT INTO BaiBao VALUES ('B2', 'BK', N'Xử lý ngôn ngữ', 'N2');

INSERT INTO THAMGIA VALUES ('B1', 'TN', 'N1', N'Giỏi');
INSERT INTO THAMGIA VALUES ('B1', 'BK', 'N1', N'Xuất sắc');
INSERT INTO THAMGIA VALUES ('B1', 'BK', 'N3', N'Khá');
INSERT INTO THAMGIA VALUES ('B2', 'BK', 'N1', N'Trung bình');
INSERT INTO THAMGIA VALUES ('B2', 'BK', 'N3', N'Khá');