--WEEK 04--
--TOPIC 4--

--Q27--
SELECT  COUNT(*) N'Số lượng giáo viên',
        SUM(GV.LUONG) N'Tổng lương'
FROM    GIAOVIEN GV;

--Q28--
SELECT  GV.MABM N'Mã bộ môn',
        COUNT(*) N'Số lượng giáo viên',
        AVG(GV.LUONG) N'Lương trung bình'
FROM    GIAOVIEN GV
GROUP BY    GV.MABM;

--Q29--
SELECT  CD.TENCD N'Tên chủ đề',
        COUNT(DT.MADT) N'Số lượng đề tài'        
FROM    CHUDE CD JOIN DETAI DT ON CD.MACD = DT.MACD
GROUP BY DT.MACD, CD.TENCD;

--Q30--
SELECT  GV.HOTEN N'Họ tên giáo viên',
        COUNT(DISTINCT TGDT.MADT) N'Số lượng đề tài'
FROM    GIAOVIEN GV LEFT JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
GROUP BY GV.MAGV, GV.HOTEN;

--Q31--
SELECT  GV.HOTEN N'Họ tên giáo viên',
        COUNT(DISTINCT DT.MADT) N'Số lượng đề tài'
FROM    GIAOVIEN GV LEFT JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY GV.MAGV, GV.HOTEN;

--Q32--
SELECT  GV.HOTEN N'Họ tên giáo viên',
        COUNT (NT.TEN) N'Số người thân'
FROM GIAOVIEN GV LEFT JOIN NGUOI_THAN NT ON GV.MAGV = NT.MAGV
GROUP BY GV.MAGV, GV.HOTEN;

--Q33--
SELECT  GV.HOTEN N'Họ tên giáo viên'
FROM    GIAOVIEN GV LEFT JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TGDT.MADT) >= 3;

--Q34--
SELECT  COUNT(DISTINCT TGDT.MAGV) N'Số lượng giáo viên'
FROM    THAMGIADT TGDT
GROUP BY TGDT.MADT
HAVING TGDT.MADT = (
    SELECT MADT
    FROM DETAI
    WHERE TENDT = N'Ứng dụng hóa học xanh'
);