--TUAN 3--

--Q17--
SELECT  CV.MADT N'Mã đề tài',
        CV.STT,
        CV.TENCV N'Tên công việc'
FROM CONGVIEC CV 
WHERE DATEDIFF(DD, '01/01/2007', CV.NGAYBD) >= 0 AND DATEDIFF(DD, '08/01/2007', CV.NGAYBD) <= 0;

--Q18--
SELECT  GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MABM = (
    SELECT MABM
    FROM GIAOVIEN
    WHERE HOTEN = N'Trần Trà Hương'
) AND GV.HOTEN != N'Trần Trà Hương';

--Q19--
SELECT DISTINCT GV.MAGV N'Mã giáo viên'
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM, DETAI DT
WHERE BM.TRUONGBM = DT.GVCNDT;

--Q20--
SELECT  GV.HOTEN N'Họ tên'
FROM GIAOVIEN GV JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA, BOMON BM
WHERE K.TRUONGKHOA = BM.TRUONGBM;

--Q21--
SELECT DISTINCT GV.HOTEN N'Họ tên giáo viên'
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM, DETAI DT
WHERE BM.TRUONGBM = DT.GVCNDT;

--Q22--
SELECT DISTINCT GV.MAGV N'Mã giáo viên'
FROM GIAOVIEN GV JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA, DETAI DT
WHERE K.TRUONGKHOA = DT.GVCNDT;

--Q23--
SELECT DISTINCT GV.MAGV N'Mã giáo viên'
FROM GIAOVIEN GV
WHERE GV.MABM = 'HTTT'
UNION
SELECT DISTINCT GV.MAGV N'Mã giáo viên'
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT = '001';

--Q24--
SELECT  GV.MAGV N'Mã giáo viên',
        GV.HOTEN N'Họ tên'
FROM GIAOVIEN GV
WHERE GV.MABM = (
    SELECT MABM
    FROM GIAOVIEN
    WHERE MAGV = '002'
) AND GV.MAGV != '002';

--Q25--
SELECT  GV.MAGV N'Mã giáo viên',
        GV.HOTEN N'Họ tên'
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM;

--Q26--
SELECT  GV.HOTEN N'Họ tên',
        GV.LUONG N'Lương'
FROM GIAOVIEN GV;